config/routes.rb
Rails.application.routes.draw do
  get 'static/about'
  get 'static/team'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#accepts one argument, a hash. key = url, value = class/method
#get({'/hello_world' => 'posts#home'})

  get '/hello_world' => 'posts#home'

  get '/posts' => 'posts#index'
  get '/posts/:id' => 'posts#show', :as => :post

  get 'about_us' => 'static#about'
  get 'team' => 'static#team'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def home
    render :plain => "Hello World"
  end

  def index

    #instance variables get passed to the views
    @posts = Post.all

    render 'posts/index'
    #render :plain => "posts"
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about
    #Implicit Rendering Convention
    #app/views/[controller_name]/[action_name].html/erb

    #app/views/static/about.html.erb
  end

  def team
    #explicitly tell it to move to the content/team folder in views instead of static
    #if implicit(it's not), it will go into static folder => team

    render 'content/team'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/content/team.html.erb
<p>yarr be the content/team</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogFlash</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>


<ol>
<% @posts.each do |post|%>
<!--using html to generate link
  <li><a href="/posts/<%= post.id %>"><%= post.title %></li> -->

    <!--more abstract -->
    <%= link_to(post.title, "/posts#{post.id}")%>

    <!-- more abstract -->
    <%= link_to(post.title, post_path(post.id))%>

    <!-- more abstract-->
    <%= link_to(post.title, post_path(post))%>

    <!-- most abstract, implicitly calling post_path and post.title -->
    <%= link_to(post.title, post)%>
  <%end%>
</ol>

<%-# action view -%>

<%= link_to("About Page", about_us_path)%>